/**
 * Detects browser & OS from the User Agent string (synchronous).
 * Used as a quick baseline; supplement with getDeviceInfoAsync() for full detail.
 */
export function getDeviceInfo() {
  const ua = navigator.userAgent;

  // ── Browser detection ──────────────────────────────────────────────────────
  let browser = 'Unknown Browser';
  if (ua.includes('Firefox')) {
    browser = 'Firefox';
  } else if (ua.includes('Edg/')) {
    browser = 'Edge';
  } else if (ua.includes('Chrome') && !ua.includes('Edg/')) {
    browser = 'Chrome';
  } else if (ua.includes('Safari') && !ua.includes('Chrome')) {
    browser = 'Safari';
  } else if (ua.includes('Opera') || ua.includes('OPR')) {
    browser = 'Opera';
  }

  // ── OS detection ───────────────────────────────────────────────────────────
  let os = 'Unknown OS';
  if (ua.includes('Windows')) {
    os = 'Windows';
  } else if (ua.includes('Mac OS X') || ua.includes('Macintosh')) {
    os = 'macOS';
  } else if (ua.includes('Android')) {
    os = 'Android';
  } else if (ua.includes('iPhone') || ua.includes('iPad')) {
    os = 'iOS';
  } else if (ua.includes('CrOS')) {
    os = 'ChromeOS';
  } else if (ua.includes('Linux')) {
    os = 'Linux';
  }

  // ── Device name (persisted in localStorage) ────────────────────────────────
  let deviceName = localStorage.getItem('kirimly_device_name');
  if (!deviceName) {
    const isDesktop =
      os === 'Windows' || os === 'macOS' || os === 'Linux' || os === 'ChromeOS';
    const prefix = isDesktop ? 'DESKTOP' : 'PHONE';
    const suffix = Math.random().toString(36).substring(2, 6).toUpperCase();
    deviceName = `${prefix}-${suffix}`;
    localStorage.setItem('kirimly_device_name', deviceName);
  }

  return { browser, os, deviceName };
}

/**
 * Async version – enriches device info with the real hardware model when the
 * browser supports the User-Agent Client Hints API (Chrome 90+, Edge 90+).
 *
 * On mobile (Android) Chrome, `ua.model` returns the actual model identifier,
 * e.g. "SM-G955U", "Pixel 7", "M2101K7AG".
 * On browsers that don't support it, it falls back to the sync result.
 *
 * The enriched device name is persisted so subsequent calls are instant.
 *
 * @returns {Promise<{ browser: string, os: string, deviceName: string, model: string }>}
 */
export async function getDeviceInfoAsync() {
  const base = getDeviceInfo(); // always get the baseline first
  let model = '';

  if (navigator.userAgentData) {
    try {
      const highEntropy = await navigator.userAgentData.getHighEntropyValues([
        'model',
        'platform',
        'platformVersion',
        'architecture',
      ]);

      model = highEntropy.model || ''; // e.g. "SM-G955U" | "Pixel 7" | "" on desktop

      console.log('[DeviceInfo] High-entropy UA data:', {
        model: highEntropy.model,
        platform: highEntropy.platform,
        platformVersion: highEntropy.platformVersion,
        architecture: highEntropy.architecture,
      });

      // If we got a real model AND the stored name still looks auto-generated,
      // replace it with the actual model string for a friendlier display.
      if (model) {
        const stored = localStorage.getItem('kirimly_device_name');
        const isAutoGenerated = /^(DESKTOP|PHONE)-[A-Z0-9]{4}$/.test(stored || '');

        if (isAutoGenerated || !stored) {
          localStorage.setItem('kirimly_device_name', model);
          base.deviceName = model;
        }
      }
    } catch (err) {
      // Permission denied or API unavailable — silently fall back
      console.warn('[DeviceInfo] getHighEntropyValues failed:', err);
    }
  }

  return { ...base, model };
}

/**
 * Returns a Material Symbols icon name for the detected OS.
 */
export function getOsIcon(os) {
  const icons = {
    Windows: 'laptop_windows',
    macOS: 'laptop_mac',
    Linux: 'computer',
    Android: 'smartphone',
    iOS: 'smartphone',
    ChromeOS: 'laptop_chromebook',
  };
  return icons[os] || 'devices';
}

/**
 * Returns a Material Symbols icon name for the detected browser.
 */
export function getBrowserIcon(browser) {
  const icons = {
    Chrome: 'language',
    Firefox: 'language',
    Safari: 'language',
    Edge: 'language',
    Opera: 'language',
  };
  return icons[browser] || 'language';
}
